### ISSUE TITLE
[REFACTO] Page Article

### ISSUE THREAD

**Issue by LuckyShuii** [WildCodeSchool/blog-e-boulga-mvc#11]
### Narration
ETQ User je désire lire un article, afin de m'instruire!

### Spec
CF article : 
https://www.figma.com/file/JEkawmwKmoZYk3KUIOhL3K/Wild-BlogeBoulga?type=design&node-id=0-1&mode=design&t=3PBBpsBBnXfJA56y-0

### Hors scope
- Navigation
- Bloc Auteur

### SubTask
- [ ] Générer l'article depuis la 
- [ ] retirer le PHP dans la page du template

Desktop

- [ ] Core

Mobile
- [ ] Core

### Critère d'acceptance
- [ ] Pas de PHP dans la page du template
- [ ] Généré depuis la DB
- [ ] Responsive

### Images
Desktop
![Image](https://github.com/WildCodeSchool/blog-e-boulga/assets/45230586/38f3a995-7164-4701-8907-917b07e598b6)

Mobile
![Image](https://github.com/WildCodeSchool/blog-e-boulga/assets/45230586/a46fe559-02f6-4b54-9196-693ba59fb1bd)
