### ISSUE TITLE
Sauvegarder en DB les données du Form

### ISSUE THREAD

**Issue by LuckyShuii** [WildCodeSchool/blog-e-boulga-mvc#41]
### Spec

- Sécurisation des données
- Pas de réel envoie
- Stocker uniquement les données en DB

### Hors scope

- Front / Visuel
- Envoi par mail

### SubTask

- [x] Créer le controller pour gérer le formulaire
- [x] Aucun PHP dans le code du template
- [x] Stocker les données en base de données

### Ressources
