### ISSUE TITLE
[GLOBAL] Définir des catégories d'articles

### ISSUE THREAD

**Issue by Monost0ne** [WildCodeSchool/blog-e-boulga-mvc#73]
### Spec
Etablir une liste de catégories pour notre MVP, exemple : "écologie, jeux vidéos, cinéma, etc"

### Hors scope
Attribuer à un article une catégorie
Modification de la DB

### SubTask
- [ ] Etablir une liste d'au moins 10 entrée
- [ ] Prévenir le groupe que la liste est établie
- [ ] Communiquer à la personne qui est sur la tâche (attribuer une catégorie à un article) la liste des catégories

### Ressources
